### ISSUE TITLE
Provide a way to reuse the library coordinate for the template, without incurring deps

### ISSUE THREAD

**Issue by SevereOverfl0w** [seancorfield/deps-new#23]
It might be useful to allow authors to reuse the coordinate of the main project for the template.  Highlighting my [own project](https://sr.ht/~severeoverfl0w/wedge/sources) there are two coordinates currently: `io.dominic/wedge` and `io.dominic/wedge-template`.  It would be nice if the coordinate was just the library coordinate though (this is why {clj,boot,lein}-new do that awful `/lein-template` business, it gives you a pretty name which matches your project).

One inspiration for this is the `:deps/prep-lib` which allows you to specify which alias to use for "building".  By using an alias for resolution, you could specify additional dependencies (e.g. mustache) which are needed when generating the template. 

I'm not sure how much I actually want this.  I don't feel strongly about having 2 coordinates.

**Comment by seancorfield** [comment]
I'm still having a hard time understanding what you're suggesting.

To have `deps-new` process a template, it needs two things: a template "name" (to produce a path to `template.edn` relative to the classpath and for that to be on the classpath :)

So, generally, you need something like:

```bash
clojure -Sdeps '{:deps {io.github.the-org/the-lib {:git/tag "v1.2.3" :git/sha "a1b2c3d"}}}' -Tnew :template some.name/space :name your.project/name
```

The coordinates exist just to get stuff on the classpath (thank you, CLI). The template name exists just to figure out the relative path to `template.edn`. There's no concept of a "project" involved -- `deps-new` doesn't know anything about how the classpath was constructed, and it doesn't use `tools.deps.alpha`, although since `tools.build` brings that in, it _could_ (but I'd rather stick with `tools.build` to create a basis). There's no `deps.edn` in play here.

**Comment by SevereOverfl0w** [comment]
Ah, I see.  I hadn't figured that out yet...  I also hadn't noticed the limitation on requiring git/local coordinates either.  Yeah, I can't see a straightforward way to handle this until tdeps supports activating aliases in other projects.

**Comment by seancorfield** [comment]
Okay to close this out then?

**Comment by SevereOverfl0w** [comment]
I think so, yeah!
