### ISSUE TITLE
It should not be necessary to use -Sdeps to reference a third-party template

### ISSUE THREAD

**Issue by hlship** [seancorfield/deps-new#55]
Currently, you must specify using -Sdeps a literal chunk of dependencies so that deps-new can find your `template.edn` (based on the :template from the command line).

As a user, I would expect `deps-new` to be able to work directly from the template, expecting the template to match a Maven artifact.  `deps-new` should be able to build a basis directly from that (after somehow figuring out the correct :mvn/version) and build a classpath from that basis.

**Comment by seancorfield** [comment]
I've updated the summary to remove the Maven reference since `deps-new` doesn't support that -- only local- and git- templates -- but the current invocation syntax is "horrible" and we can do better.

`tools.deps` includes code to infer `:git/url` and `tools.gitlibs` includes code to resolve branch names and tags to actual SHAs, so between those two, `deps-new` should be able to get close to something like `io.github.orgname/some-repo` with a default name assumed for the template itself within that repo, which can be overridden.

Syntax for the "template name" needs to include ways to supply:
* a way to infer the `:git/url`
* a way to infer/override the path to `template.edn` in the repo
* a way to specify `:deps/root` if needed
* a way to specify particular versions/tags/SHAs if needed

**Comment by seancorfield** [comment]
The commit unconditionally requires Clojure 1.12 in order to do the dynamic addition of dependencies via `clojure.repl.deps/add-lib`. The code needs to be cleaned up to still work with Clojure 1.11 (without the dynamic addition), and documentation added to the README to explain how to force the tool to run with 1.12.

See also https://clojure.atlassian.net/jira/software/c/projects/TDEPS/issues/TDEPS-258 -- if that is fixed, then `deps-new` _could_ depend directly on 1.12 and not need the workaround (or the changes to still work with 1.11) but it's not clear when that will get fixed.

**Comment by seancorfield** [comment]
I'm considering this addressed in v0.7.0 which I just released.
